### ISSUE TITLE
로그인 기능 구현 확장 (/sign) - JWT Access & Refresh Token + 쿠키 적용

### ISSUE THREAD

**Issue by dameun0527** [dameun0527/Onboarding_java#8]
### 개요
- 기존 로그인 기능 (#5 )에서 **Refresh Token을 적용하고, 쿠키를 활용하여 보안을 강화**
- Access Token과 Refresh Token을 함께 발급하여 **세션 유지를 가능하게 함**.

### 변경된 내용
1. **JWT Access & Refresh Token 동시 발급**
   - 기존에는 **Access Token만 발급**했지만, 이제 **Refresh Token도 함께 발급**
   - `JWTUtil.createToken("access", username, role, 600000L)` → Access Token (10분 유효)
   - `JWTUtil.createToken("refresh", username, role, 86400000L)` → Refresh Token (1일 유효)

2. **Refresh Token을 `HttpOnly` 쿠키에 저장**
   - 기존에는 **Access Token만 응답 헤더에 포함**했지만, 이제 **Refresh Token을 `HttpOnly` 쿠키에 저장**
   - 쿠키 설정:
     ```java
     response.addCookie(CookieUtil.createCookie("refresh", newRefreshToken));
     ```

   - `HttpOnly` 속성을 추가하여 클라이언트에서 직접 접근할 수 없도록 보안 강화

3. **Refresh Token을 DB에 저장**
   - 로그인 시, **Refresh Token을 DB에 저장하여 관리**함.
   - 기존 Refresh Token이 있다면 삭제 후 새로운 값으로 저장 (`refreshService.saveRefreshToken()` 사용)

4. **로그인 응답 변경**
   - **Access Token은 여전히 응답 헤더에 포함**되지만, **Refresh Token은 쿠키에 저장됨**.
   - Request body:
     ```json
     {
       "username": "JIN HO",
       "password": "12341234"
     }
     ```

   - Response body:
     ```
     Headers:
     - access-token: eKDIkdfjoakIdkfjpekdkcjdkoIOdjOKJDFOlLDKFJKL

     Cookies:
     - refreshToken=OQJDFOlLDKFJKLdjokjfkdjpekdkcjdko; HttpOnly; Secure
     ```

5. **테스트 및 예외 처리**
   - 로그인 시 Refresh Token이 정상적으로 쿠키에 저장되는지 확인
   - Refresh Token이 DB에 정상적으로 저장되는지 확인
   - 기존 로그인 방식 (`#5`)과 비교하여 정상 동작하는지 테스트

### 진행 상황
- [x] Refresh Token을 발급 및 쿠키에 저장
- [x] Refresh Token을 DB에 저장 및 관리
- [ ] 로그인 API 응답 변경 (헤더 + 쿠키)
- [x] 예외 처리 및 유닛 테스트 작성
- [x] PR 작성 및 리뷰 요청

### 관련 Issue
- `#5` 로그인 기능 구현 (/sign)
